### ISSUE TITLE
<br> wont work as yours?

### ISSUE THREAD

**Issue by chinobing** [jimmybow/tree_vis#1]
```
data['nodes'] = [{'id' : i, 'hidden': False, 'show_leaf': True,
                  'title' : 'Gini impurity = ' + str(Tree.tree_.impurity[i]) +
                  '<br>samples = ' + str(int(Tree.tree_.weighted_n_node_samples[i])) +
                  '<br>( ' + ', '.join(Tree.classes_ + ' = ' + Tree.tree_.value[i][0].astype(int).astype(str)) + ' )'
                                     }  for i in range(Tree.tree_.node_count)] 
```
I try to add `<br>` into the 'title' to break lines as you did, but it does not work as yours. It just simply prints out `Gini impurity.... <br>samples ..... ` without breaking the line.

And if I separate my items into two colors(red, green), how can I put them side by side(red on the left side, green on the right side of the graph)?

**Comment by jimmybow** [comment]
you may need to add the css to show the tooltips
```
my_css_url = "https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.css"
app.css.append_css({
    "external_url": my_css_url
})
```

**Comment by chinobing** [comment]
thanks for your reply. I will try it. btw, I really like your Dash Core Components. Thanks for your hardwork!!! I used your visdcc to make a dash aspp. here is what it looks like．http://www.fundviz.com/industry

**Comment by jimmybow** [comment]
WOW, it's really cool ...
您太強啦 !
